### ISSUE TITLE
Task 003 - Analysis report D01.

### ISSUE THREAD

**Issue by laurolmer** [laurolmer/Acme-L3-D01#3]
Produce an analysis report regarding this deliverable.

**Comment by Albertoperleo** [comment]
Acabo de terminar de redactar el informe, @laurolmer échale un vistazo!!

**Comment by laurolmer** [comment]
Todo correcto.

**Comment by Albertoperleo** [comment]
Hemos tenido que reabrir este issue debido a que había que corregir unos apartados.
