### ISSUE TITLE
Task 004 - Planning report D01.

### ISSUE THREAD

**Issue by laurolmer** [laurolmer/Acme-L3-D01#4]
Produce a planning report.

**Comment by Albertoperleo** [comment]
@laurolmer he realizado cambios dentro del documento de Excel para hacer un buen cálculo de los beneficios del proyecto. Revísalo y me comentas qué te va pareciendo. 

#### Cambios realizados
- Añadidos los diferentes roles con sus respectivos sueldos/hora.
- Añadidos campos modificables de horas trabajadas para que se puedan ajustar los cálculos.
- Añadido el cálculo del sueldo bruto mensual (respecto a las horas trabajadas) y anual.
- Añadido el cálculo de coste total de los sueldos brutos.
- Añadido el cálculo del coste social (30%).
- Añadido el cálculo del coste social total.

#### Falta por hacer
- Cálculo del beneficio total.
- Cálculo de la amortización lineal.

Quedan algunas cosas más por hacer para tener el cálculo del presupuesto grupal completo, pero se irá viendo conforme vayamos completando lo expuesto en la lista anterior.

**Comment by Albertoperleo** [comment]
@laurolmer he estado añadiendo los cálculos que faltaban en el excel. Además, he añadido:
- Hoja de cálculo del presupuesto individual para que cada uno pueda introducir sus datos y obtener su presupuesto.
- Hoja con cálculo de burndown del proyecto para saber cómo avanzamos respecto a un "desarrollo ideal"
